from typing import Tuple, List, Dict, Any

class Type:
    def __str__(self) -> str: ...
    def uid(self) -> str: ...

class Term:
    def __str__(self) -> str: ...
    def uid(self) -> str: ...

class Node:
    def __str__(self) -> str: ...
    def uid(self) -> str: ...
    def properties(self) -> Dict[str, Any]: ...

class Edge:
    def __str__(self) -> str: ...
    def uid(self) -> Tuple[str, str]: ...
    def properties(self) -> Dict[str, Any]: ...

type Element = Type | Term | Node | Edge

class Query:
    def __str__(self) -> str: ...
    def execute(self) -> None: ...
    def return_(self, *variables: str) -> List[Dict[str, Element]]: ...
    def match(self, pattern: str) -> "Query": ...
    def create(self, pattern: str) -> "Query": ...
    def remove(self, *variables: str) -> "Query": ...
    def set(self, variable: str, properties: Dict[str, Any]) -> "Query": ...

class Graph:
    def __init__(self) -> None: ...
    def query(self) -> Query: ...
    def nodes(self) -> List[Node]: ...
    def edges(self) -> List[Edge]: ...
