from typing import Tuple, List, Dict, Any, Optional

class Type:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def uid(self) -> str: ...

class Term:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def uid(self) -> str: ...

class Node:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def uid(self) -> str: ...
    def properties(self) -> Dict[str, Any]: ...
    def type(self) -> Type: ...
    def term(self) -> Optional[Term]: ...

class Edge:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def uid(self) -> Tuple[str, str]: ...
    def properties(self) -> Dict[str, Any]: ...
    def type(self) -> Type: ...
    def term(self) -> Term: ...

type Element = Type | Term | Node | Edge

class Constant:
    name: str
    def __init__(self, name: str, type_schema: str) -> None: ...

class Query:
    def __str__(self) -> str: ...
    def execute(self) -> None: ...
    def return_(self, *variables: str) -> List[Dict[str, Element]]: ...
    def match(self, pattern: str) -> "Query": ...
    def create(self, pattern: str) -> "Query": ...
    def remove(self, *variables: str) -> "Query": ...
    def set(self, variable: str, properties: Dict[str, Any], overwrite: bool = True) -> "Query": ...

class Graph:
    def __init__(self, constants: List[Constant] = []) -> None: ...
    def query(self) -> Query: ...
    def nodes(self) -> List[Node]: ...
    def edges(self) -> List[Edge]: ...
    def set_node_properties(self, map: Dict[str, Dict[str, Any]], overwrite: bool = True): ...
    def set_edge_properties(
        self, map: Dict[Tuple[str, str], Dict[str, Any]], overwrite: bool = True
    ): ...
